FROM timescale/timescaledb-ha:pg17

# Expose PostgreSQL port
EXPOSE 5432

# Set default environment variables
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres

# Use the default entrypoint from the TimescaleDB image
