name: DB CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  migrate-and-seed:
    runs-on: ubuntu-latest

    services:
      timescaledb:
        image: timescale/timescaledb-ha:pg17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tsdb
        ports:
          - 25432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v6

      - name: Sqitch install
        run: docker pull sqitch/sqitch && curl -L https://git.io/JJKCn -o /usr/local/bin/sqitch && chmod +x /usr/local/bin/sqitch && sqitch --help

      - name: Setup DB
        run: |
          docker run --rm --network host postgres:17-alpine psql \
            "postgresql://postgres:postgres@localhost:25432/postgres" \
            -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='tsdbadmin') THEN CREATE ROLE tsdbadmin LOGIN SUPERUSER PASSWORD 'tsdbadmin'; ELSE ALTER USER tsdbadmin WITH PASSWORD 'tsdbadmin'; END IF; END \$\$;"

      - name: Timescale Migrations
        run: |
          cd sqitch && sqitch deploy "db:pg://tsdbadmin:tsdbadmin@localhost:25432/tsdb" \
            --set flows_password=flows \
            --set grafanareader_password=grafanareader \
            --set tableau_password=tableau \
            --set env=local \
            --verbose && cd -

      - name: Flows Seed
        run: |
          docker run --rm --network host \
            -v "$(pwd)/sqitch/seed:/seed" postgres:17-alpine \
            psql "postgresql://tsdbadmin:tsdbadmin@localhost:25432/tsdb" \
            -f /seed/seed.sql
