name: DB CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  # Tell Sqitch where to find secrets - in this case we just use the example secrets
  SQITCH_USER_CONFIG: 'sqitch_secrets.conf.example'

jobs:
  migrate-and-seed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sqitch install
        run: sudo apt-get install sqitch libdbd-pg-perl postgresql-client libdbd-sqlite3-perl sqlite3 && sqitch --help
      - name: Start Timescale
        run: bin/ts-up
      # Looking at the logs it takes about 15 seconds so give a little buffer.
      # IF we don't do this the migrations below fail.
      - name: Wait Timescale
        run: sleep 25
      - name: Timescale Migrations
        run: cd sqitch && sqitch deploy --target self-hosted-timescale-local --verbose && cd -

      # uncomment the following to be able to ssh in and investigate an issue:
      #
      # - name: Setup tmate session
      #   if: success() || failure()
      #   uses: mxschmitt/action-tmate@v3
      
      - name: create .pgpass for seed script
        run: mkdir -p /tmp/psql-script/ && echo "*:*:postgres:postgres:postgres" > /tmp/psql-script/.pgpass && chmod 0600 /tmp/psql-script/.pgpass
      - name: Flows Seed
        run: bin/ts-seed
